### ISSUE TITLE
Build error while installing.

### ISSUE THREAD

**Issue by muzam1l** [dimapaloskin/playcap#5]
So it fails on installing with following error log. I have VS2017 installed via `windows-build-tools`.

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.c
  napi_utils.c
  utils.c  
  context.c
  device.c 
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(39): error C2057: expected constant expression [C:\Users\muzam\code\ex
tensions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(39): error C2466: cannot allocate an array of constant size 0 [C:\User
s\muzam\code\extensions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(39): error C2133: 'outputData': unknown size [C:\Users\muzam\code\exte
nsions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(40): error C2057: expected constant expression [C:\Users\muzam\code\ex
tensions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(40): error C2466: cannot allocate an array of constant size 0 [C:\User
s\muzam\code\extensions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(40): error C2133: 'inputData': unknown size [C:\Users\muzam\code\exten
sions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(85): error C2057: expected constant expression [C:\Users\muzam\code\ex
tensions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(85): error C2466: cannot allocate an array of constant size 0 [C:\User
s\muzam\code\extensions\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\device.c(85): error C2133: 'argv': unknown size [C:\Users\muzam\code\extensions
\saturday\node_modules\playcap\build\playcap.vcxproj]
c:\users\muzam\code\extensions\saturday\node_modules\playcap\src\context.c(52): error C2059: syntax error: '}' [C:\Users\muzam\code\extensions\s
aturday\node_modules\playcap\build\playcap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\muzam\code\extensions\saturday\node_modules\playcap
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN acorn-import-assertions@1.7.6 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
npm WARN saturday@0.0.1 No repository field.
npm WARN saturday@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playcap@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by muzam1l** [comment]
So it's basically issues related to initializing variable size array of pointers, which can be better maintained by allocating memory through `malloc` or just using c99 in compiler flags. I can make a pull request to implement that, if you want.

**Comment by dimapaloskin** [comment]
Hello @muzam1l. Sorry for the delay. 
Unfortunately, I didn't test it on a windows machine, so yes, if it possible, please make a PR.

Thank you :)

**Comment by ser0ja** [comment]
i get an error when installing on windows

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.  
addon.c  
napi_utils.c  
utils.c    
context.c  
f:\dropbox\development\javascript\si\node_modules\playcap\src\context.c(52): error C2059: syntax error: '}' F:\Dropbox\Development\javascript\si\node_modules\playcap\build\playcap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe failed with exit code: 1
```

```
gyp info using node-gyp@8.4.1
gyp info using node@17.5.0 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Program Files\Python310\python.exe"
gyp info find VS using VS2022 (17.1.32210.238) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
```
